//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< Updated upstream
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
=======
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
>>>>>>> Stashed changes
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BD.Properties {
    using System;
    
    
    /// <summary>
<<<<<<< Updated upstream
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
=======
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
>>>>>>> Stashed changes
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
=======
        ///   Returns the cached ResourceManager instance used by this class.
>>>>>>> Stashed changes
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_BD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
=======
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
>>>>>>> Stashed changes
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
>>>>>>> Stashed changes
        /// </summary>
        internal static System.Drawing.Bitmap _666175_optimized_1_optimized_1_optimized_1_optimized {
            get {
                object obj = ResourceManager.GetObject("666175_optimized_1_optimized_1_optimized_1_optimized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
>>>>>>> Stashed changes
        /// </summary>
        internal static System.Drawing.Bitmap console__3_ {
            get {
                object obj = ResourceManager.GetObject("console (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
>>>>>>> Stashed changes
        /// </summary>
        internal static System.Drawing.Bitmap leftarrow_1_optimized_1_optimized_1_optimized {
            get {
                object obj = ResourceManager.GetObject("leftarrow_1_optimized_1_optimized_1_optimized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
=======
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
>>>>>>> Stashed changes
        /// </summary>
        internal static System.Drawing.Bitmap leftarrow_1_optimized_1_optimized_1_optimized1 {
            get {
                object obj = ResourceManager.GetObject("leftarrow_1_optimized_1_optimized_1_optimized1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
